apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vzn2j7qpy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vzn2j7qpy-nodejs 
  name: vzn2j7qpy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vzn2j7qpy-nodejs 
